services:
  app:
    ports:
      - "8000:8000"
    command: sh -c "php artisan serve --host=0.0.0.0"
    environment:
      FRONTEND_URL: "http://localhost:3000"
  frontend:
    command: sh -c "npm install && vue serve"
    ports:
      - "3000:3000"
