# ./nginx/default.conf

server {
    listen 80;
    server_name localhost;

    charset utf-8;
    client_max_body_size 20M;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    root /var/www/public;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ ^/api {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }

    # -------------------------------------------------------------------------
    # FRONTEND: SPA Vue.js 2
    # -------------------------------------------------------------------------
    location / {
        root /var/www/html/public/spa;
        index index.html;
        
        # CRUCIAL: Vue Router's 'History Mode' requires this configuration to work properly. 
        # If the static route does not exist on disk, it sends the request to index.html
        # This is necessary so that Vue.js can handle routing in the browser.
        try_files $uri $uri/ /index.html;
    }

    # Redirect all other errors to the SPA's index.html, so that Vue Router can handle them.
    # error_page 404 /index.html;
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}